server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/authservice
    username: root
    password: Qwerty1,0*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serializer.StringSerializer
      value-serializer: com/sc/authservice/serializer/UserInfoSerializer.java
    #Custom
    topic:
      name: ExpenseApp-Auth

# Custom
application:
  security:
    jwt:
      secret-key: qMB1ZJDi3lRW92LuQ8Hzb6eoU41Ny3x3ioowN2JNaFeBJ6bSvnOr1/xLwprKB2py