server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/authservice
    username: root
    password: Qwerty1,0*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Custom
application:
  security:
    jwt:
      secret-key: 78EC211A54A5C8A636A215F8EFC72