server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:authservice}
    username: root
    password: Qwerty1,0*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.sc.authservice.serializer.UserInfoSerializer
    #Custom
    topic:
      name: ExpenseApp-Auth

# Custom
application:
  security:
    jwt:
      secret-key: qMB1ZJDi3lRW92LuQ8Hzb6eoU41Ny3x3ioowN2JNaFeBJ6bSvnOr1/xLwprKB2py