server:
  port: 8083

spring:
  application:
    name: EXPENSE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/expenseservice
    username: root
    password: Qwerty1,0*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: expense-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.sc.expenseservice.consumer.ExpenseDeserializer
      #Custom
    topic:
      name: ExpenseApp-Auth